[project]
name = "structural-therapy"
version = "0.1.0"
description = "Structural Therapy app scaffolded with uv, Streamlit, and LangGraph"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit",
    "langgraph",
    "langchain-openai",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8",
    "ruff>=0.5",
]
